example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here

from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
# TODO: Implement Routings Here

from django.urls import path
from mywatchlist.views import *

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('html/', show_html, name='show_html'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
from turtle import up
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import add_task
from todolist.views import todolist_json
from todolist.views import create_task_ajax
from todolist.views import update
from todolist.views import delete_todolist


app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add_task/', add_task, name='add_task'),
    path('json/', todolist_json, name='todolist_json'),
    path('create-task-ajax/', create_task_ajax, name="create_task_ajax"),
    path('update/', update, name="update"),
    path('delete/', delete_todolist, name="delete_todolist")
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.TextField()
    rating = models.TextField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
import datetime
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today)
    title = models.CharField(max_length=100)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import Task

class Input_Form(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']
    
    

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.

def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
        'list_barang': data_barang_katalog,
        'nama': 'Diah Afia Safitri'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from email import message
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

# TODO: Create your views here.

def show_mywatchlist(request):
    data_film_mywatchlist = MyWatchList.objects.all()
    context = {
        'list_film': data_film_mywatchlist,
        'nama': 'Diah Afia Safitri'
    }
    return render(request, "mywatchlist.html", context)

def show_html(request):
    data_film_mywatchlist = MyWatchList.objects.all()
    watched = 0
    not_watched = 0
    for film in data_film_mywatchlist:
        if film.watched :
            watched = watched + 1
        else :
            not_watched = not_watched + 1
        
    if watched > not_watched:
        message = "Selamat kamu sudah banyak menonton anime"
    else :
        message = "kamu masih kurang menonton anime"
    context = {
        'list_film': data_film_mywatchlist,
        'message' : message
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from todolist.models import Task
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from todolist.forms import Input_Form
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    task_todolist = Task.objects.filter(user = request.user)
    context = {
        'task_list' : task_todolist
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('todolist:login')

def add_task(request):
    if request.method == "POST":
        task_form = Input_Form(request.POST)
        if task_form.is_valid():
            task_form.instance.user = request.user
            task_form.save()
            messages.success(request, 'Task berhasil ditambahkan :)')
            return redirect ('todolist:show_todolist')
    context = {
        'task_list ':'task_todolist',
    }
    return render(request, 'add_task.html', context)

@login_required(login_url='/todolist/login/')
@csrf_exempt
def update(request, id):
    item = Task.objects.get(pk=id)
    finished = not item.is_finished
    item.is_finished = finished
    item.save()
    return JsonResponse({"is_finished": finished})
    
@login_required(login_url='/todolist/login/')
@csrf_exempt
def delete_todolist(request, id):
    todolist = Task.objects.get(pk=id)
    todolist.delete()
    return redirect('todolist:show_todolist')

def todolist_json(request):
    data = Task.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
@csrf_exempt
def create_task_ajax(request):
    if request.method == "POST":
        user = request.user
        title = request.POST.get("title")
        description = request.POST.get("description")
        create_new_task = Task(user=user, title=title, description=description)
        create_new_task.save()

        return JsonResponse({"pk" : create_new_task.pk, "fields": {
            "date" : create_new_task.date,
            "title" : create_new_task.title,
            "description" : create_new_task.description,
        }})

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>FDiah Afia Safitri</p>

  <h5>Student ID: </h5>
  <p>2106750420</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
      <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.item_url}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3</h1>
  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for film in list_film %}
      <tr>
        <th>{{film.watched}}</th>
        <th>{{film.title}}</th>
        <th>{{film.rating}}</th>
        <th>{{film.release_date}}</th>
        <th>{{film.review}}</th>
      </tr>
    {% endfor %}
  </table>
  <h1>{{message}}<h1>
 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <style>
    * {
      box-sizing: border-box;
    }
    
    body {
      font-family: Arial, Helvetica, sans-serif;
    }
    .column {
      float: left;
      width: 33%;
      padding: 12px;
      align:center;
    }

    .row {
      margin: 0 -5px;
      padding: 10px;
    }
    
    .row:after {
      content: "";
      display: table;
      clear: both;
    }
    
    @media screen and (max-width: 600px) {
      .column {
        width: 100%;
        display: block;
        margin-bottom: 20px;
      }
    }
    
    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      padding: 16px;
      text-align: center;
      background-color: #f1f1f1;
      border-radius: 18px; 
      margin:0 auto;
      float:none;
    }
    .cards {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      padding: 16px;
      text-align: center;
      background-color: #f1f1f1;
      border-radius: 18px; 
      margin:0 auto;
      float:none;
    }
    .card:hover {
      transform: scale(1.05);
      box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
    }
    .button:hover {
      border-radius: 8px; 
      background-color:#191970;
      transition: 0.7s;
    }
    </style>
    {% block meta %}
    {% endblock meta %}
</head>

<body style="background: -webkit-gradient(linear, left top, left bottom, from(#b0e0e6), to(#a9a9a9)) fixed;">
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
</body>

</html>

todolist/templates/add_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}


<div class="container" style="width:320px; padding-top:50px;">
    <div class="card" style="width: 20rem; ">
        <h1 style="text-align:center; font: bold 23px/1 sans-serif;">ADD TASK</h1>
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Title: </td>
                    <td><input type="text" name="title" placeholder="Title" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Description: </td>
                    <td><input type="text" name="description" placeholder="Description" class="form-control"></td>
                </tr>

                <tr>
                    <td><input class="btn add_task_btn" type="submit" value="Add"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %} 
    </div>    
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="container" style="width:320px; padding-top:50px;">
    <div class="card" style="width: 20rem; ">
        <h1 style="text-align:center; font: bold 23px/1 sans-serif;">LOGIN</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group">
                <label style="padding-top: 10px">Username</label>
                <input type="text" name="username" placeholder="Username" size="40" class="form-control">
            </div>
                    
            <div class="form-group">
                <label style="padding-top: 10px">Password</label>
                <input type="password" name="password" placeholder="Password" size="40" class="form-control">
            </div>

            <div style="text-align:center">
                <button class="btn btn-primary" type="submit" style="margin-top: 10px"> Login </button>
            </div>
        </form>
    </div>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    <div class="text-center" style="font: bold 24px/1 sans-serif;">
        <h6 style="font: bold 15px/1 sans-serif; padding-top:10px; text-align:center;">Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a></h6>
    </div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class="container" style="width:320px; padding-top:50px;">
    <div class="card" style="width: 50rem; ">
        <h1 class="text-2xl font-bold mb-4">Formulir Registrasi</h1>  
            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr class="mt-2 flex flex-col justify-center items-center">  
                        <td></td>
                        <td><input type="submit" name="submit" value="Daftar"/></td>  
                    </tr>  
                </table>  
            </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}
    </div>
</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $.get(window.location.href + "json/", function (data) {
      for (idx = 0; idx < data.length; idx++) {
        getData(data[idx]);
        deleteData(data[idx]);
        updateStatus(data[idx]);
      }
    });

    function getData(data) {
      $("#container").append(
        `
        <div id="${data.pk}-card" class="column">
            <div class="card" style="width: 18rem; ">
                <div class="card-header" style="border-radius: 25px;">
                <h5 class="card-title" style="background-color: #f5fffa; border-radius: 25px; font-weight: bold;">${data.fields.title}</h5>
                </div>
                <p>${data.fields.description}</p>
                <p>${data.fields.date}</p>
                <p id="${data.pk}-status">${data.fields.is_finished ? "selesai": "belum selesai"}</p>
                <a id="${data.pk}-update" class="btn btn-success"> Update Status </a>
                <a id="${data.pk}-delete" class="btn btn-success"> delete </a>
            </div>
        </div>   
                `
      );
    }

    $("#create-new").submit(function (e) {
        e.preventDefault();
        $.post(window.location.href + "create-task-ajax/", {
          title: $("#title").val(),
          description: $("#description").val(),
        }).done(function (data) {
          getData(data);
          deleteData(data);
          updateStatus(data);
          $("#title").val(""), $("#description").val("");
          const sectionCards = document.getElementById("container");
          sectionCards.insertAdjacentHTML("beforestart", $(`#${data.pk}-card`));
        });
      });

    function updateStatus(data) {
      $(`#${data.pk}-update`).click(function () {
        $.post(window.location.href + `update/${data.pk}/`, {}).done(
          (res) => {
            const statusTodolist = res.is_finished
              ? "selesai"
              : "belum selesai";
            $(`#${data.pk}-status`).text(statusTodolist);
          }
        );
      });
    }

    function deleteData(data) {
      $(`#${data.pk}-delete`).click(function () {
        $.post(window.location.href + `delete/${data.pk}/`, {}).done(
          (res) => {
            $(`#${data.pk}-card`).fadeOut();
          }
        );
      });
    }
  });
</script>
{% endblock meta %}
 
{% block content %}

<nav class="navbar">
    <div class="m-3 d-flex flex-column justify-content-between align-items-center">
        <h5 class="text-black" style="font: bold 24px/1 sans-serif; background-color: #d3d3d3; border-radius: 10px; padding:10px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2)">username</h5>
        <h5 class="text-white">{{request.user}}</h5>
    </div>
</nav>

<div class="m-3 d-flex flex-row justify-content-between">
    <div class="button">
        <button type="button" class="btn btn-dark"><a class="text-white text-decoration:none;" href="{% url 'todolist:logout' %}">Logout</a></button>
    </div>
</div>

<div class="container" style="padding : 20px;">
    <div id="container" class="row">
   
        <!-- <div class="column">
            <div class="card" style="width: 18rem; ">
                <div class="card-header" style="border-radius: 25px;">
                <h5 class="card-title" style="background-color: #f5fffa; border-radius: 25px; font-weight: bold;">{{task.title}}</h5>
                </div>
                <p>{{task.description}}</p>
                <p>{{task.date}}</p>
                <p>{{task.is_finished}}</p>
            </div>
        </div> -->
    
    </div>
</div>

<div class="m-3 d-flex flex-row justify-content-between"></div>
    <div class="card" style="width: 18rem; ">
    <form id="create-new" method="POST" action="">
        {% csrf_token %}
        <table>
            <tr> </tr>
            <tr>
                <td>Title: </td>
                <td><input id="title" type="text" name="title" placeholder="Title" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Description: </td>
                <td><input id="description" type="text" name="description" placeholder="Description" class="form-control"></td>
            </tr>

            <tr>
                <td><input class="btn add_task_btn" type="submit" value="Add"></td>
            </tr>
        </table>
    </form>
    </div>
</div>

{% comment %}
<table class="table table-striped table-bordered">
    <tr class="table-dark">
        <th>Title</th>
        <th>Description</th>
        <th>Date Created</th>
    </tr>
    {% for task in task_list %}
        <tr>
            <td>{{task.title}}</td>
            <td>{{task.description}}</td>
            <td>{{task.date}}</td>
        </tr>
    {% endfor %}
</table>
{% endcomment %}

{% endblock content %}